package minesweeper

fun main() {
    println("""
        .....X...
        ...X.....
        .X....X..
        ....X....
        ..XX.....
        .........
        ..X...X..
        .........
        ..X......
    """.trimIndent())
}
